import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from "react";
import { DEFAULT_VIDEO_QUEUE_MAX_BYTES, PlayerEngine } from "./engine";
import type { H422PlayerHandle, H422PlayerProps } from "./types";

export const H422Player = forwardRef<H422PlayerHandle,H422PlayerProps>(function H422Player({src,autoPlay=false,controls=true,muted=false,mode="legacy",videoRenderMode="yuv-webgl",libavBase="/libav",videoQueueMaxBytes,fullDecodeMaxRate,enableMemoryAdaptiveBuffer,memoryCheckIntervalMs,memoryHighWaterRatio,memoryLowWaterRatio,memoryShrinkFactor,memoryGrowFactor,minVideoAheadSeconds,minVideoQueueMaxBytes,minRetainBehindSeconds,fallbackVideoAheadSeconds,fallbackVideoQueueMaxBytes,enableAudioLevels=false,audioLevelIntervalMs,className,onReady,onMediaInfo,onTimecode,onSeekingChange,onBufferingChange,onDiagnostics,onTimeUpdate,onStatusChange,onStateChange,onPlaybackRateChange,onAudioLevelUpdate,onError},ref){
  const canvas=useRef<HTMLCanvasElement>(null), engine=useRef<PlayerEngine|null>(null); const [playing,setPlaying]=useState(false); const [time,setTime]=useState(0); const [duration,setDuration]=useState(0);
  // The engine outlives a render, so its callbacks read the latest props through a ref rather than
  // closing over the ones the effect happened to see. Level updates arrive several times a second;
  // a stale closure there would report to a handler the host has already replaced.
  const handlers=useRef({onReady,onMediaInfo,onTimecode,onSeekingChange,onBufferingChange,onDiagnostics,onTimeUpdate,onStatusChange,onStateChange,onPlaybackRateChange,onAudioLevelUpdate,onError});
  handlers.current={onReady,onMediaInfo,onTimecode,onSeekingChange,onBufferingChange,onDiagnostics,onTimeUpdate,onStatusChange,onStateChange,onPlaybackRateChange,onAudioLevelUpdate,onError};
  const autoPlayRef=useRef(autoPlay); autoPlayRef.current=autoPlay;
  useEffect(()=>{if(!canvas.current)return;const e=new PlayerEngine(canvas.current,{status:s=>{setPlaying(s==="playing");handlers.current.onStatusChange?.(s);},state:value=>handlers.current.onStateChange?.(value),ready:i=>{setDuration(i.duration);handlers.current.onReady?.(i);if(autoPlayRef.current)void e.play();},mediaInfo:i=>handlers.current.onMediaInfo?.(i),timecode:value=>handlers.current.onTimecode?.(value),seeking:value=>handlers.current.onSeekingChange?.(value),buffering:value=>handlers.current.onBufferingChange?.(value),diagnostics:value=>handlers.current.onDiagnostics?.(value),playbackRate:(rate,info)=>handlers.current.onPlaybackRateChange?.(rate,info),audioLevels:levels=>handlers.current.onAudioLevelUpdate?.(levels),time:t=>{setTime(t);handlers.current.onTimeUpdate?.(t);},error:x=>handlers.current.onError?.(x)},muted,libavBase,{}, {mode,videoRenderMode,videoQueueMaxBytes,fullDecodeMaxRate,enableMemoryAdaptiveBuffer,memoryCheckIntervalMs,memoryHighWaterRatio,memoryLowWaterRatio,memoryShrinkFactor,memoryGrowFactor,minVideoAheadSeconds,minVideoQueueMaxBytes,minRetainBehindSeconds,fallbackVideoAheadSeconds,fallbackVideoQueueMaxBytes,enableAudioLevels,audioLevelIntervalMs});engine.current=e;void e.load(src).catch(()=>{});return()=>e.destroy();
  // enableAudioLevels and audioLevelIntervalMs seed the engine but are deliberately not dependencies:
  // toggling a meter must not reload the file. The toggle is applied by the effect below instead.
  },[src,muted,mode,videoRenderMode,libavBase,videoQueueMaxBytes,fullDecodeMaxRate,enableMemoryAdaptiveBuffer,memoryCheckIntervalMs,memoryHighWaterRatio,memoryLowWaterRatio,memoryShrinkFactor,memoryGrowFactor,minVideoAheadSeconds,minVideoQueueMaxBytes,minRetainBehindSeconds,fallbackVideoAheadSeconds,fallbackVideoQueueMaxBytes]);
  useEffect(()=>{engine.current?.setAudioLevelsEnabled(enableAudioLevels);},[enableAudioLevels]);
  useImperativeHandle(ref,()=>({play:()=>engine.current?.play()??Promise.resolve(),pause:()=>engine.current?.pause(),seek:t=>engine.current?.seek(t)??Promise.resolve(),seekTimecode:t=>engine.current?.seekTimecode(t)??Promise.resolve(),stepFrame:frames=>engine.current?.stepFrame(frames)??Promise.resolve(),seekRelative:seconds=>engine.current?.seekRelative(seconds)??Promise.resolve(),setPlaybackRate:rate=>engine.current?.setPlaybackRate(rate)??Promise.resolve(),get playbackRate(){return engine.current?.playbackRate??1},get currentTime(){return engine.current?.currentTime??0},get duration(){return engine.current?.duration??0},get state(){return engine.current?.state??"idle"},get audioLevelsEnabled(){return engine.current?.audioLevelsEnabled??false},getAudioLevels:()=>engine.current?.getAudioLevels()??null,setAudioLevelsEnabled:value=>engine.current?.setAudioLevelsEnabled(value),getDiagnostics:()=>engine.current?.getDiagnostics()??{mode:"legacy",videoRenderMode:"rgba",fileSize:0,bytesLoaded:0,underlyingReadCount:0,cacheBytes:0,videoQueueFrames:0,videoQueueStart:null,videoQueueEnd:null,scheduledAudioRanges:0,loadGeneration:0,seekGeneration:0,streamingAudioSupported:false,selectedAudioTrackNumber:null,audioSampleRate:null,audioChannels:null,audioQueueStart:null,audioQueueEnd:null,audioVideoDriftMs:null,audioBytesLoaded:0,audioQueuedThroughTime:0,audioExhausted:false,lastPlayableAudioTime:null,audioFormatBasis:null,requestedTimecode:null,requestedFrame:null,actualDisplayedFrame:null,seekStartFrame:null,prerollFrames:0,seekSource:null,seekReadBytes:0,seekElapsedMs:null,selectedTimecodeTrack:null,timecodeSelectionReason:"Timecode Trackなし",videoDecodedFrames:0,videoDecodeMs:0,videoColorConvertMs:0,videoUploadMs:0,decoderExecution:"dedicated-worker",rendererBackend:"webgl",playbackRate:1,frameSelection:"all-frames",audioPlaybackRate:1,adaptiveVideoAheadSeconds:6,adaptiveRefillThresholdSeconds:4,adaptiveRetainBehindSeconds:1,videoQueueBytes:0,videoQueueMaxBytes:DEFAULT_VIDEO_QUEUE_MAX_BYTES,adaptiveVideoQueueMaxBytes:DEFAULT_VIDEO_QUEUE_MAX_BYTES,lastChunkDecodeMs:0,pooledVideoFrames:0,memoryApiAvailable:false,jsHeapUsedBytes:null,jsHeapLimitBytes:null,jsHeapAvailableBytes:null,memoryBufferAdjustmentCount:0,memoryBufferAdjustments:[],bufferingEventCount:0,bufferingTotalMs:0}}),[]);
  return <div className={className} style={{background:"#000",display:"inline-block"}}><canvas ref={canvas} style={{display:"block",maxWidth:"100%"}} />{controls&&<div style={{display:"flex",gap:8,padding:8}}><button type="button" onClick={()=>playing?engine.current?.pause():void engine.current?.play()}>{playing?"Pause":"Play"}</button><input aria-label="Seek" type="range" min={0} max={duration||0} step="any" value={time} onChange={e=>void engine.current?.seek(Number(e.target.value))} style={{flex:1}}/><span style={{color:"white"}}>{time.toFixed(1)} / {duration.toFixed(1)}</span></div>}</div>;
});
