import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from "react";
import { PlayerEngine } from "./engine";
import type { H422PlayerHandle, H422PlayerProps } from "./types";

export const H422Player = forwardRef<H422PlayerHandle,H422PlayerProps>(function H422Player({src,autoPlay=false,controls=true,muted=false,mode="legacy",libavBase="/libav",className,onReady,onMediaInfo,onTimecode,onSeekingChange,onBufferingChange,onDiagnostics,onTimeUpdate,onStatusChange,onError},ref){
  const canvas=useRef<HTMLCanvasElement>(null), engine=useRef<PlayerEngine|null>(null); const [playing,setPlaying]=useState(false); const [time,setTime]=useState(0); const [duration,setDuration]=useState(0);
  useEffect(()=>{if(!canvas.current)return;const e=new PlayerEngine(canvas.current,{status:s=>{setPlaying(s==="playing");onStatusChange?.(s);},ready:i=>{setDuration(i.duration);onReady?.(i);if(autoPlay)void e.play();},mediaInfo:i=>onMediaInfo?.(i),timecode:value=>onTimecode?.(value),seeking:value=>onSeekingChange?.(value),buffering:value=>onBufferingChange?.(value),diagnostics:value=>onDiagnostics?.(value),time:t=>{setTime(t);onTimeUpdate?.(t);},error:x=>onError?.(x)},muted,libavBase,{}, {mode});engine.current=e;void e.load(src).catch(()=>{});return()=>e.destroy();},[src,muted,mode,libavBase]);
  useImperativeHandle(ref,()=>({play:()=>engine.current?.play()??Promise.resolve(),pause:()=>engine.current?.pause(),seek:t=>engine.current?.seek(t)??Promise.resolve(),seekTimecode:t=>engine.current?.seekTimecode(t)??Promise.resolve(),get currentTime(){return engine.current?.currentTime??0},get duration(){return engine.current?.duration??0},getDiagnostics:()=>engine.current?.getDiagnostics()??{mode:"legacy",fileSize:0,bytesLoaded:0,underlyingReadCount:0,cacheBytes:0,videoQueueFrames:0,videoQueueStart:null,videoQueueEnd:null,scheduledAudioRanges:0,loadGeneration:0,seekGeneration:0,streamingAudioSupported:false,selectedAudioTrackNumber:null,audioSampleRate:null,audioChannels:null,audioQueueStart:null,audioQueueEnd:null,audioVideoDriftMs:null,audioBytesLoaded:0,audioQueuedThroughTime:0,audioExhausted:false,lastPlayableAudioTime:null,audioFormatBasis:null,requestedTimecode:null,requestedFrame:null,actualDisplayedFrame:null,seekStartFrame:null,prerollFrames:0,seekSource:null,seekReadBytes:0,seekElapsedMs:null,selectedTimecodeTrack:null,timecodeSelectionReason:"Timecode Trackなし"}}),[]);
  return <div className={className} style={{background:"#000",display:"inline-block"}}><canvas ref={canvas} style={{display:"block",maxWidth:"100%"}} />{controls&&<div style={{display:"flex",gap:8,padding:8}}><button type="button" onClick={()=>playing?engine.current?.pause():void engine.current?.play()}>{playing?"Pause":"Play"}</button><input aria-label="Seek" type="range" min={0} max={duration||0} step="any" value={time} onChange={e=>void engine.current?.seek(Number(e.target.value))} style={{flex:1}}/><span style={{color:"white"}}>{time.toFixed(1)} / {duration.toFixed(1)}</span></div>}</div>;
});
